# Generated by Django 4.2.4 on 2023-08-21 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0004_alter_app_user_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_sending', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sending_user', to=settings.AUTH_USER_MODEL)),
                ('user_sent_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_sent_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
