# Generated by Django 4.2.4 on 2023-08-21 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_friend_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend_request',
            name='user_sending',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sending_user', to='login.app_user'),
        ),
        migrations.AlterField(
            model_name='friend_request',
            name='user_sent_to',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_sent_to', to='login.app_user'),
        ),
    ]
