# Generated by Django 4.2.4 on 2023-08-21 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_friend_request_user_sending_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend_request',
            name='user_sending',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_sent', to='login.app_user'),
        ),
        migrations.AlterField(
            model_name='friend_request',
            name='user_sent_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_received', to='login.app_user'),
        ),
    ]
